apiVersion: v1
kind: ServiceAccount
metadata:
  name: evolven-collector-admin
  namespace: sock-shop 
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-binding
subjects:
- kind: ServiceAccount
  name: evolven-collector-admin
  namespace: sock-shop
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
